version: '3.7'

services:
  jango:
    build: ./jango
    container_name: jango_web
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./jango/.env

  svelte:
    build: ./svelte
    container_name: svelte_web
    command: node build
    expose:
      - 3000
    env_file:
      - ./svelte/.env