version: '3.7'

services:
  jango:
    build: ./jango
    container_name: jango_web
    command: gunicorn jango.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./jango/.env
    depends_on:
      - migration
  migration:
    build: ./jango
    container_name: jango_web
    command: python manage.py migrate --noinput
  svelte:
    build: ./svelte
    container_name: svelte_web
    command: forever build
    expose:
      - 3000
    env_file:
      - ./svelte/.env