# Generated by Django 3.1.4 on 2022-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_auto_20220816_0917"),
    ]

    operations = [
        migrations.RemoveField(model_name="tag", name="nfts",),
        migrations.AddField(
            model_name="nft",
            name="tags",
            field=models.ManyToManyField(to="marketplace.Tag"),
        ),
    ]
