# Generated by Django 3.1.4 on 2022-08-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_auto_20220816_0924"),
    ]

    operations = [
        migrations.RemoveField(model_name="collection", name="nft",),
        migrations.AddField(
            model_name="nft",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfts",
                to="marketplace.collection",
            ),
        ),
        migrations.AddField(
            model_name="nft",
            name="owner",
            field=models.CharField(default="0x", max_length=64),
        ),
    ]
