# Generated by Django 4.1 on 2022-08-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0006_nft_verified_alter_adminwallet_id_alter_attribute_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Permanent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commission_on_nft_in_bnb", models.IntegerField(default=3)),
                ("nftl_value", models.IntegerField(default=3)),
                ("divided_by", models.IntegerField(default=3)),
                ("bnb_value", models.IntegerField(default=3)),
            ],
        ),
    ]
