# Generated by Django 4.1 on 2022-08-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_permanent"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft", name="is_active", field=models.BooleanField(default=True),
        ),
    ]
