# Generated by Django 4.1 on 2022-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_nft_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="creator",
            field=models.CharField(default="0x", max_length=64),
        ),
    ]
