# Generated by Django 4.1 on 2022-08-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_alter_nft_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nft", old_name="is_listed", new_name="is_hidden",
        ),
    ]
