# Generated by Django 3.1.4 on 2022-06-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookie", "0003_book_ticket_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="display_pourcentage",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TicketCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adress", models.CharField(max_length=63)),
                (
                    "bent_on",
                    models.CharField(
                        choices=[
                            ("team1", "Team 1"),
                            ("team2", "Team 2"),
                            ("null", "Null"),
                        ],
                        default="team1",
                        max_length=6,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_count",
                        to="bookie.book",
                    ),
                ),
            ],
        ),
    ]
