# Generated by Django 3.1.4 on 2022-06-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookie", "0005_ticketcount_amount"),
    ]

    operations = [
        migrations.RemoveField(model_name="ticketcount", name="book",),
    ]
