# Generated by Django 3.1.4 on 2022-06-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookie", "0006_remove_ticketcount_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketcount", old_name="adress", new_name="address",
        ),
    ]
