# Generated by Django 3.1.4 on 2022-06-13 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookie", "0008_auto_20220613_0903"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcount",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
